image: mcr.microsoft.com/dotnet/sdk:10.0

stages:
  - build
  - validate
  - test

variables:
  GITLAB_DOCKER_PROXY: gitlab.education.tbank.ru:443/backend-academy-dotnet-2025/lecture-materials/dependency_proxy/containers


build:
  stage: build
  script:
    - dotnet build
  only:
    - merge_requests


linter:
  stage: validate
  script:
    - dotnet format --verify-no-changes
  only:
    - merge_requests


module_test:
  stage: test
  needs:
    - job: build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"
      when: always
      allow_failure: false
    - when: never
  script:
    - dotnet test src/LinkTracker.Tests.Unit/LinkTracker.Tests.Unit.csproj

integration_test:
  image: docker:29.0.1-cli
  stage: test
  needs:
    - job: module_test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH == "master"
      when: always
      allow_failure: false
    - when: never
  tags:
    - dind
  services:
    - name: docker:29.0.1-dind
      alias: docker
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  script:
    - until [ -f /certs/client/ca.pem ]; do echo "waiting docker certs"; sleep 1; done
    - docker version
    - docker build -t link-tracker-scrapper:latest -f src/LinkTracker.Scrapper/Dockerfile .
    - docker build -t link-tracker-bot:latest -f src/LinkTracker.Bot/Dockerfile .
    - docker build -t link-tracker-bot.migrator:latest -f src/LinkTracker.Bot.Migrator/Dockerfile .
    - docker build -t link-tracker-scrapper.migrator:latest -f src/LinkTracker.Scrapper.Migrator/Dockerfile .
    - docker run --rm --add-host docker:host-gateway -v "$PWD:/src" -w /src -e DOCKER_HOST=tcp://docker:2376 -e DOCKER_TLS_VERIFY=1 -e DOCKER_CERT_PATH=/certs/client -e TESTCONTAINERS_HOST_OVERRIDE=docker -v /certs/client:/certs/client:ro mcr.microsoft.com/dotnet/sdk:10.0 dotnet test src/LinkTracker.Tests.IntegrationTests/LinkTracker.Tests.IntegrationTests.csproj


  