<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\LinkTracker.AiAgent.Application\LinkTracker.AiAgent.Application.csproj" />
      <ProjectReference Include="..\LinkTracker.AiAgent.Contracts\LinkTracker.AiAgent.Contracts.csproj" />
      <ProjectReference Include="..\LinkTracker.AiAgent.Domain\LinkTracker.AiAgent.Domain.csproj" />
      <ProjectReference Include="..\LinkTracker.Bot.Contracts\LinkTracker.Bot.Contracts.csproj" />
      <ProjectReference Include="..\LinkTracker.Scrapper.Contracts\LinkTracker.Scrapper.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" Version="2.14.0" />
      <PackageReference Include="Confluent.SchemaRegistry" Version="2.14.0" />
      <PackageReference Include="Confluent.SchemaRegistry.Serdes.Avro" Version="2.14.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
      <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.8" />
      <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
    </ItemGroup>

</Project>
