<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f85fee1f-a611-4ba5-b8d7-6eb7d0b221be</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.34.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.76.0" />
    <PackageReference Include="Grpc.Tools" Version="2.78.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="10.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkTracker.Scrapper.Application\LinkTracker.Scrapper.Application.csproj" />
    <ProjectReference Include="..\LinkTracker.Scrapper.Contracts\LinkTracker.Scrapper.Contracts.csproj" />
    <ProjectReference Include="..\LinkTracker.Scrapper.Infrastructure\LinkTracker.Scrapper.Infrastructure.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\LinkTracker.Scrapper.Contracts\Grpc\scrapper_link.proto" GrpcServices="Server" />
	</ItemGroup>

</Project>
