<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="InterfacesRepositories\" />
    <Folder Include="Repositories\" />
    <Folder Include="InterfacesServices\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkTracker.Scrapper.Domain\LinkTracker.Scrapper.Domain.csproj" />
  </ItemGroup>

</Project>
