syntax = "proto3";

option csharp_namespace = "LinkTracker.Scrapper.Contracts.Grpc";

package scrapper;

service ScrapperService
{
  rpc RegisterChat(RegisterChatRequest) returns (Empty);

  rpc DeleteChat(DeleteChatRequest) returns (Empty);

  rpc ExistChat(ExistChatRequest) returns (ExistChatResponse);

  rpc AddLink(AddLinkRequest) returns (LinkResponse);

  rpc RemoveLink(RemoveLinkRequest) returns (LinkResponse);

  rpc GetLinks(GetLinksRequest) returns (ListLinksResponse);
}

message Empty {}

message RegisterChatRequest {
  int64 chatId = 1;
}

message DeleteChatRequest {
  int64 chatId = 1;
}

message ExistChatRequest {
  int64 chatId = 1;
}

message ExistChatResponse {
  bool existChat = 1;
}

message AddLinkRequest {
  int64 chatId = 1;
  string url = 2;
  repeated string tags = 3;
}

message RemoveLinkRequest {
  int64 chatId = 1;
  string url = 2;
}

message GetLinksRequest {
  int64 chatId = 1;
  string tag = 2;
}

message ExistChatResponse {
  bool existChat = 1;
}

message AddLinkRequest {
  int64 chatId = 1;
  string url = 2;
  repeated string tags = 3;
}

message RemoveLinkRequest {
  int64 chatId = 1;
  string url = 2;
}

message GetLinksRequest {
  int64 chatId = 1;
  string tag = 2;
}