<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkTracker.Bot.Contracts\LinkTracker.Bot.Contracts.csproj" />
    <ProjectReference Include="..\LinkTracker.Bot.Domain\LinkTracker.Bot.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
    <Folder Include="InterfacesRepositories\" />
    <Folder Include="InterfacesServices\" />
    <Folder Include="Mappers\" />
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
